# Generated by Django 4.1.2 on 2022-10-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_quiz_timer',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_id',
            field=models.CharField(choices=[('ed674e61d1', 'ed674e61d1')], max_length=255, unique=True),
        ),
    ]
