# Generated by Django 4.1.2 on 2022-10-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_topic_topic_quiz_timer_alter_topic_topic_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_quiz_timer',
        ),
        migrations.AddField(
            model_name='quiz',
            name='timer',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_id',
            field=models.CharField(choices=[('487d70bad9', '487d70bad9')], max_length=255, unique=True),
        ),
    ]
