# Generated by Django 4.1.2 on 2022-10-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_topic_topic_quiz_timer_quiz_timer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
