# Generated by Django 4.1.2 on 2022-10-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_topic_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='procent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
