# Generated by Django 4.1.2 on 2022-10-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_student_procent'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_over_ball_procent',
            field=models.IntegerField(default=50, verbose_name="O'tish ball prosenti"),
        ),
    ]
