# Generated by Django 4.1.2 on 2022-10-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_topic_topic_over_ball_procent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_over_ball_procent',
            field=models.IntegerField(default=50, help_text='foyizda kiriting', verbose_name="O'tish ball foyizi"),
        ),
    ]
