# Generated by Django 4.1.2 on 2022-10-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_topic_topic_over_ball_procent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
